#!/usr/bin/env bash

cp /autograder/submission/sqlfiles.zip /autograder/source/sqlfiles.zip

cd /autograder/source

unzip sqlfiles.zip

node processSqlJS.js

cd ../autograder

jest

cp ./results/results.json  /autograder/results/results.json

